version: '3.8'

services:
  web:
    build: ./backend/
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOUR_PASSWORD
      - POSTGRES_DB=postgres

  frontend:
    build: ./frontend/
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - web
    
volumes:
  postgres_data:
